const SUPABASE_URL="https://zafgfjsdzfknqljjbumv.supabase.co",SUPABASE_KEY="sb_publishable_WsUdEATeL5sDRIwfJxoxIw_iBwxGAdo";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function refresh(){const s=(await db.auth.getSession()).data.session;if(!s)return;const today=new Date().toISOString().slice(0,10);const [p,e,d]=await Promise.all([db.from("photos").select("*").eq("status","pending").order("created_at",{ascending:false}),db.from("events").select("*").order("event_date",{ascending:false}),db.from("donors").select("*").order("created_at",{ascending:false})]);const photos=p.data||[],events=e.data||[],donors=d.data||[],total=donors.reduce((a,x)=>a+(Number(x.amount)||0),0);dashDonations.textContent="₹"+total.toLocaleString("en-IN",{maximumFractionDigits:2});dashDonors.textContent=donors.length;dashEvents.textContent=events.filter(x=>x.event_date===today).length;dashPending.textContent=photos.length;pendingPhotos.innerHTML=photos.length?photos.map(x=>`<div class="pending-item"><img src="${esc(x.image_url)}"><div><b>${esc(x.title||"Untitled photo")}</b><br>Uploaded by: ${esc(x.uploaded_by||"Not provided")}</div><div class="actions"><button onclick="approve('${x.id}')">Approve</button> <button class="danger" onclick="rejectPhoto('${x.id}')">Reject</button></div></div>`).join(""):"<p class='muted'>No photos waiting for approval.</p>";adminEvents.innerHTML=events.length?`<table class="small-table"><tr><th>Date</th><th>Event</th><th>Location</th></tr>${events.map(x=>`<tr><td>${esc(x.event_date)}</td><td>${esc(x.title)}</td><td>${esc(x.location||"")}</td></tr>`).join("")}</table>`:"<p class='muted'>No events yet.</p>";adminDonors.innerHTML=donors.length?`<table class="small-table"><tr><th>Donor</th><th>Amount</th></tr>${donors.map(x=>`<tr><td>${x.is_anonymous?"Anonymous Donor":esc(x.name)}</td><td>${x.amount!=null?"₹"+Number(x.amount).toLocaleString("en-IN"):"—"}</td></tr>`).join("")}</table>`:"<p class='muted'>No donors yet.</p>"}async function approve(id){await db.from("photos").update({status:"approved"}).eq("id",id);refresh()}async function rejectPhoto(id){await db.from("photos").delete().eq("id",id);refresh()}
loginForm.addEventListener("submit",async e=>{e.preventDefault();const r=await db.auth.signInWithPassword({email:email.value,password:password.value});if(r.error){loginMsg.textContent=r.error.message;return}showDash()});logoutBtn.addEventListener("click",async()=>{await db.auth.signOut();location.reload()});
async function showDash(){loginPanel.hidden=true;dashboard.hidden=false;refresh()}db.auth.onAuthStateChange((_e,s)=>{if(s)showDash()});
eventForm.addEventListener("submit",async e=>{e.preventDefault();const r=await db.from("events").insert({title:eventTitle.value.trim(),description:eventDesc.value.trim(),event_date:eventDate.value,start_time:startTime.value||null,end_time:endTime.value||null,location:eventLocation.value.trim()});alert(r.error?r.error.message:"Event saved successfully.");if(!r.error)e.target.reset();refresh()});
donorForm.addEventListener("submit",async e=>{e.preventDefault();const r=await db.from("donors").insert({name:donorName.value.trim(),amount:donorAmount.value?Number(donorAmount.value):null,is_anonymous:donorAnonymous.checked});alert(r.error?r.error.message:"Donor saved successfully.");if(!r.error)e.target.reset();refresh()});
announcementForm.addEventListener("submit",async e=>{e.preventDefault();const r=await db.from("announcements").insert({title:annTitle.value.trim(),message:annMessage.value.trim()});alert(r.error?r.error.message:"Announcement saved successfully.");if(!r.error)e.target.reset()});
(async()=>{if((await db.auth.getSession()).data.session)showDash()})();